import Head from 'next/head'
import Navbar from '../components/navbar'
import InputField from '../components/inputField'
import { useState } from 'react';
import { useRouter } from 'next/router'
import ConfirmarSenha from './confirmarSenha';
import AlterarSenha from './alterarSenha';

export default function Perfil() {

    const router = useRouter()

    const [data, setData] = useState({
        nome: "João",
        sobrenome: "Pacheco Ferreira",
        matricula: "0020012000",
        email: "fulano@edu.pe.senac.br",
        senha: "325235"
    });

    const changeInputValue = (e) => {
        setData({ ...data, [e.target.name]: e.target.value });
    }

    // Modal de confirmar senha

    const [isModalConfirmarSenha, setModalConfirmarSenha] = useState(false);

    function openModalConfirmarSenha() { setModalConfirmarSenha(true) }

    function closeModalConfirmarSenha() { setModalConfirmarSenha(false) }


    // Modal de alterar senha

    const [isModalAlterarSenha, setModalAlterarSenha] = useState(false);

    function openModalAlterarSenha() { setModalAlterarSenha(true) }

    function closeModalAlterarSenha() { setModalAlterarSenha(false) }

    return (
        <>

            {
                isModalConfirmarSenha ? (
                    <ConfirmarSenha dataPerfil={data} closeModalConfirmarSenha={closeModalConfirmarSenha} />
                ) : null
            }

            {
                isModalAlterarSenha ? (
                    <AlterarSenha closeModalAlterarSenha={closeModalAlterarSenha} />
                ) : null
            }
            <Head>
                <title>Senacalls</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="manifest" href="/manifest.json" />
                <meta name="theme-color" content="#317EFB" />
            </Head>

            <div className="flex flex-col min-h-screen">
                <div className="flex-grow mb-28">
                    <Navbar />
                    <main className="flex items-center justify-center flex-col w-full ">
                        <h1 className="flex justify-start w-4/5 m-4 text-lg">Dados do Perfil</h1>
                        <section className='w-4/5 flex items-center justify-center flex-col'>
                            <div className='my-4 flex items-center justify-center'>
                                <img src="/perfil.png" alt="Foto de perfil do usuário" />
                            </div>
                            <section className='my-6 flex items-center justify-center flex-col'>
                                <div className='my-1 flex items-center justify-evenly flex-row w-full'>
                                    <section className='flex items-center justify-center w-full'>
                                        <InputField
                                            title={'Nome'}
                                            type={'text'}
                                            name={'nome'}
                                            id={'nome'}
                                            placeholder={data.nome}
                                            value={data.nome}
                                            onChange={changeInputValue}
                                        />
                                    </section>
                                    <section className='flex items-center justify-center w-full'>
                                        <InputField
                                            title={'Sobrenome'}
                                            type={'text'}
                                            name={'sobrenome'}
                                            id={'sobrenome'}
                                            placeholder={data.sobrenome}
                                            value={data.sobrenome}
                                            onChange={changeInputValue}
                                        />
                                    </section>
                                </div>
                                <div className='my-1 flex items-center justify-evenly flex-row w-full'>
                                    <section className='flex items-center justify-center w-full'>
                                        <InputField
                                            title={'Matrícula'}
                                            type={'text'}
                                            name={'matricula'}
                                            id={'matricula'}
                                            placeholder={data.matricula}
                                            value={data.matricula}
                                            onChange={changeInputValue}
                                        />
                                    </section>
                                    <section className='flex items-center justify-center w-full'>
                                        <InputField
                                            title={'E-mail'}
                                            type={'email'}
                                            name={'email'}
                                            id={'email'}
                                            placeholder={data.email}
                                            value={data.email}
                                            onChange={changeInputValue}
                                        />
                                    </section>

                                </div>

                                <div className='flex items-center justify-center w-11/12'>
                                    <h2 className="flex justify-start w-full py-2">Senha</h2>
                                    <button onClick={openModalAlterarSenha} className='flex justify-end text-xs text-senac-blue'>Alterar</button>
                                </div>
                                <input
                                    type="password"
                                    name='senha'
                                    id='senha'
                                    placeholder={data.senha}
                                    value={data.senha}
                                    onChange={changeInputValue}
                                    className="m-1.5 p-4 rounded-lg border-2 w-11/12 border-senac-yellow-40"
                                    style={{ pointerEvents: "none" }}
                                />


                            </section>
                            <button onClick={openModalConfirmarSenha} className="my-6 text-sm bg-senac-yellow-70 w-24 h-10 text-white flex items-center justify-center rounded-lg">
                                Salvar
                            </button>
                        </section>
                    </main>
                </div>

            </div>

            <section className="fixed bottom-0 bg-white flex w-full flex-col">
                <footer className=" w-4/6 flex items-center justify-around flex-row py-4">
                    <button onClick={() => router.back()} className="w-16 h-16 flex items-center justify-center rounded-full">
                        <img className="h-7 w-7" src="/backIcon.svg" alt="Icone de ok, indicando check, na cor branca" />
                    </button>
                    <a href="/">
                        <div className="w-16 h-16 flex items-center justify-center">
                            <img className="h-7 w-7" src='/homeIcon.svg' alt="Icone de seta, indicando voltar, na cor laranja" />
                        </div>
                    </a>

                </footer>
            </section>
        </>
    )
}
